### ISSUE TITLE
Malware Detected 

### ISSUE THREAD

**Issue by XurrencyFX** [relloccate/sshonix#4]
wow lol 💀
https://www.virustotal.com/graph/g11130ff303a74d3f96d5673a23320c9cf59e6ee8e17841aabc025b55e6c75861
![g11130ff303a74d3f96d5673a23320c9cf59e6ee8e17841aabc025b55e6c75861

https://www.virustotal.com/graph/embed/g11130ff303a74d3f96d5673a23320c9cf59e6ee8e17841aabc025b55e6c75861?theme=dark

**Comment by relloccate** [comment]
Hello, I can't see the pages that you sent me. If you're still here. Could you provide screenshots of what name the app is identified as viral.

It's an Electron-based app. Anything in common with this topic? https://github.com/electron-userland/electron-builder/issues/6474
